"""
run_pipeline.py — Build the warehouse from raw CSVs and answer all 10 business questions.

Equivalent to:
    duckdb olist.duckdb < sql/01_load_raw.sql
    duckdb olist.duckdb < sql/02_dim_model.sql
    duckdb olist.duckdb < sql/03_business_questions.sql

But split-aware: 03 has 10 standalone queries, each is captured separately and
written as a markdown report to outputs/business_answers.md.

Usage:
    py -3.12 src/run_pipeline.py
"""

from __future__ import annotations

import re
from pathlib import Path

import duckdb
import pandas as pd

DB_PATH = "olist.duckdb"
SQL_DIR = Path("sql")
OUT_DIR = Path("outputs")
OUT_DIR.mkdir(exist_ok=True)


def run_script(con: duckdb.DuckDBPyConnection, path: Path) -> None:
    print(f"  {path.name} ...")
    con.execute(path.read_text(encoding="utf-8"))


def split_business_questions(text: str) -> list[tuple[str, str]]:
    """Each Q is preceded by `-- Q<n>. Title`. We split on those markers."""
    # Find all `-- Q\d+. Title` headers along with their position
    pattern = re.compile(r"(?m)^--\s*(Q\d+\.\s*[^\n]+)$")
    matches = list(pattern.finditer(text))
    out: list[tuple[str, str]] = []
    for i, m in enumerate(matches):
        title = m.group(1).strip()
        body_start = m.end()
        body_end = matches[i + 1].start() if i + 1 < len(matches) else len(text)
        body = text[body_start:body_end]
        # Remove comment lines and banner dashes
        sql_lines = []
        for line in body.splitlines():
            stripped = line.strip()
            if stripped.startswith("--") or set(stripped) == {"-"} or stripped == "":
                continue
            sql_lines.append(line)
        sql = "\n".join(sql_lines).strip().rstrip(";")
        if sql:
            out.append((title, sql))
    return out


def main() -> None:
    Path(DB_PATH).unlink(missing_ok=True)
    print(f"Building warehouse in {DB_PATH}")
    con = duckdb.connect(DB_PATH)

    print("\n[1/3] Loading raw CSVs")
    run_script(con, SQL_DIR / "01_load_raw.sql")

    print("\n[2/3] Building Kimball model")
    run_script(con, SQL_DIR / "02_dim_model.sql")

    print("\n[3/3] Answering 10 business questions")
    q_text = (SQL_DIR / "03_business_questions.sql").read_text(encoding="utf-8")
    questions = split_business_questions(q_text)

    report_path = OUT_DIR / "business_answers.md"
    with report_path.open("w", encoding="utf-8") as fh:
        fh.write("# Olist — Business Question Answers\n\n")
        fh.write("Generated by `src/run_pipeline.py` against the synthetic dataset.\n\n")
        for title, sql in questions:
            print(f"  {title}".encode("ascii", "replace").decode())
            df = con.execute(sql).df()
            fh.write(f"## {title}\n\n")
            fh.write(df.head(20).to_markdown(index=False, floatfmt=",.2f"))
            fh.write("\n\n")

    print(f"\nWrote {report_path}")

    # Headline stats for the README
    print("\nHeadline stats:")
    headline = con.execute("""
        WITH o AS (
            SELECT * FROM analytics.fact_orders WHERE order_status = 'delivered'
        )
        SELECT
            COUNT(*)                                          AS orders,
            COUNT(DISTINCT customer_key)                      AS customers,
            ROUND(SUM(gross_revenue), 2)                      AS revenue_brl,
            ROUND(AVG(review_score), 2)                       AS avg_review,
            ROUND(AVG(CASE WHEN delivery_lag_days > 0 THEN 1.0 ELSE 0.0 END), 4) AS pct_late,
            ROUND(AVG(fulfillment_days), 1)                   AS avg_fulfillment_days,
            ROUND(AVG(CASE WHEN review_score <= 2 THEN 1.0 ELSE 0.0 END), 4) AS pct_low_review
        FROM o
    """).df()
    print(headline.T.to_string(header=False))
    headline.to_csv(OUT_DIR / "headline_stats.csv", index=False)

    # Revenue-at-risk number (used in MEMO)
    risk = con.execute("""
        SELECT ROUND(SUM(gross_revenue), 2) AS revenue_at_risk_late_orders
        FROM analytics.fact_orders
        WHERE order_status = 'delivered' AND delivery_lag_days > 0
    """).df()
    print("\nRevenue tied up in late deliveries (proxy for at-risk):")
    print(risk.to_string(index=False))

    con.close()


if __name__ == "__main__":
    main()
